### ISSUE TITLE
support __SOURCE_DIRECTORY__ and __SOURCE_FILE__

### ISSUE THREAD

**Issue by smoothdeveloper** [adamralph/dotnet-scripting-dialect#6]
In F# both those symbols resolve to folder of file (without trailing /) or file name (without path, unlike what is stated on doc) of file:

https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/source-line-file-path-identifiers

**Comment by adamralph** [comment]
@smoothdeveloper these symbols seems to be something built into F# itself. Are you proposing that they be added to C#?

**Comment by smoothdeveloper** [comment]
@adamralph I'm proposing for their usage to be supported at least in dotnet scripting environments that are being discussed in this repository.

**Comment by adamralph** [comment]
@smoothdeveloper I see. I think, at the moment, that's probably outside the scope of what we're trying to achieve here. After all, `__SOURCE_DIRECTORY__` and `__SOURCE_FILE__` are currently valid C# identifiers and are not special cased during compilation. As I understand it, they are special cased by the F# compiler itself, so the equivalent would be something inside the C# compiler (Roslyn). If you want those symbols specifically then I would pursue this with the Roslyn team.

That said, if you are not bothered about the specific implementation, and all you need is *some* way to get a reference to the current source file path, this could be provided through via the globals type which is used to compile the script. That is certainly a candidate for inclusion in some version of a standard scripting dialect.

**Comment by adamralph** [comment]
BTW - @smoothdeveloper please see the [readme](https://github.com/adamralph/dotnet-scripting-dialect/blob/beef972b180adf58f7caa5f193155557cfc91fad/README.md) for the current proposal for what is included in a script dialect. The proposal to special case certain identifiers is new, and I said, I doubt it's something we'll pursue here. It's probably something to take up with the Roslyn team, to get it built into the compiler itself.

**Comment by smoothdeveloper** [comment]
@adamralph understood, thanks.

Is this repository going to be a source of information / compounded overview documentation about the different scripting dialect?

It might be interesting for example to have a matrix showing how you resolve script file name, script file directory in each scripting engine, and complete that matrix with other pieces of information.

**Comment by adamralph** [comment]
@smoothdeveloper 

> is this repository going to be a source of information / compounded overview documentation about the different scripting dialect?

It's actually little more than that. It's an attempt to define the concept of a ".NET scripting dialect". I.e. for different runners such as Cake, csi, fsi, scriptcs, dotnet-script, etc. each of them has different capabilities in terms of the globals type, `#` directives, default assembly references, default namespace imports etc. The idea of a .NET scripting dialect is a medium by which to capture the various capabilities of a given runner, as well as "standard" dialects which each runner can choose to conform to, plus it's own extensions, which make up it's specific dialect. Listing the various dialects would probably a natural thing to do here as part of this work.

> It might be interesting for example to have a matrix showing how you resolve script file name, script file directory in each scripting engine, and complete that matrix with other pieces of information.

That would probably be a valuable exercise, as part of working toward the definition of the concept of a .NET scripting dialect.
